blank_issues_enabled: false
contact_links:
  - name: T4+ Community Support
    url: https://github.com/tcubed/community/discussions
    about: Please ask and answer questions here.
  - name: T4+ Security Bug Bounty
    url: https://bounty.tcubed.co/
    about: Please report security vulnerabilities here.
